name: CDK Express Pipeline Synth Action
runs:
  using: composite
  steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Set up node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm
    - name: Install dependencies
      run: npm ci
      shell: bash
    - name: CDK synth dev
      shell: bash
      run: npm run cdk -- synth '**' -c env=dev --output=cdk.out/dev
    - name: CDK synth prod
      shell: bash
      run: npm run cdk -- synth '**' -c env=prod --output=cdk.out/prod
    - name: Cache Build
      uses: actions/cache/save@v4
      with:
        key: cache-build-${{ github.sha }}
        path: |-
          cdk.out/
          node_modules/
