name: CDK Express Pipeline Diff - Dev
on:
  pull_request:
    branches:
      - main
jobs:
  synth__dev:
    name: Synth dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run CDK Express Pipeline Synth
        uses: ./.github/actions/cdk-express-pipeline-synth
        with:
          command: npm run cdk -- synth --all --output=cdk.out/dev
          cloud-assembly-directory: cdk.out/dev

  diff__dev:
    name: ${{ matrix.job-name }}
    needs:
      - synth__dev
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      id-token: write
      pull-requests: write
    strategy:
      matrix:
        include:
          - job-name: Diff dev - wave1___stage1
            cloud-assembly-directory: cdk.out/dev
            stack-selector-patterns: Wave1_Stage1_*
            command: npm run cdk -- diff Wave1_Stage1_* --app=cdk.out/dev
            assume-role-arn: arn:aws:iam::581184285249:role/githuboidc-git-hub-deploy-role
            assume-region: us-east-1
          - job-name: Diff dev - wave1___stage2
            cloud-assembly-directory: cdk.out/dev
            stack-selector-patterns: Wave1_Stage2_*
            command: npm run cdk -- diff Wave1_Stage2_* --app=cdk.out/dev
            assume-role-arn: arn:aws:iam::581184285249:role/githuboidc-git-hub-deploy-role
            assume-region: us-east-1
          - job-name: Diff dev - wave2___stage1
            cloud-assembly-directory: cdk.out/dev
            stack-selector-patterns: Wave2_Stage1_*
            command: npm run cdk -- diff Wave2_Stage1_* --app=cdk.out/dev
            assume-role-arn: arn:aws:iam::581184285249:role/githuboidc-git-hub-deploy-role
            assume-region: us-east-1
      fail-fast: false
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run CDK Express Pipeline Synth
        uses: ./.github/actions/cdk-express-pipeline-diff
        with:
          job-name: ${{ matrix.job-name }}
          stack-selector-patterns: ${{ matrix.stack-selector-patterns }}
          cloud-assembly-directory: ${{ matrix.cloud-assembly-directory }}
          command: ${{ matrix.command }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          assume-role-arn: ${{ matrix.assume-role-arn }}
          assume-region: ${{ matrix.assume-region }}

  synth__prod:
    name: Synth prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run CDK Express Pipeline Synth
        uses: ./.github/actions/cdk-express-pipeline-synth
        with:
          command: npm run cdk -- synth --all --output=cdk.out/prod
          cloud-assembly-directory: cdk.out/prod

  diff__prod:
    name: ${{ matrix.job-name }}
    needs:
      - synth__prod
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      id-token: write
      pull-requests: write
    strategy:
      matrix:
        include:
          - job-name: Diff prod - wave1___stage1
            cloud-assembly-directory: cdk.out/prod
            stack-selector-patterns: Wave1_Stage1_*
            command: npm run cdk -- diff Wave1_Stage1_* --app=cdk.out/prod
            assume-role-arn: arn:aws:iam::581184285249:role/githuboidc-git-hub-deploy-role
            assume-region: us-east-1
          - job-name: Diff prod - wave1___stage2
            cloud-assembly-directory: cdk.out/prod
            stack-selector-patterns: Wave1_Stage2_*
            command: npm run cdk -- diff Wave1_Stage2_* --app=cdk.out/prod
            assume-role-arn: arn:aws:iam::581184285249:role/githuboidc-git-hub-deploy-role
            assume-region: us-east-1
          - job-name: Diff prod - wave2___stage1
            cloud-assembly-directory: cdk.out/prod
            stack-selector-patterns: Wave2_Stage1_*
            command: npm run cdk -- diff Wave2_Stage1_* --app=cdk.out/prod
            assume-role-arn: arn:aws:iam::581184285249:role/githuboidc-git-hub-deploy-role
            assume-region: us-east-1
      fail-fast: false
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run CDK Express Pipeline Synth
        uses: ./.github/actions/cdk-express-pipeline-diff
        with:
          job-name: ${{ matrix.job-name }}
          stack-selector-patterns: ${{ matrix.stack-selector-patterns }}
          cloud-assembly-directory: ${{ matrix.cloud-assembly-directory }}
          command: ${{ matrix.command }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          assume-role-arn: ${{ matrix.assume-role-arn }}
          assume-region: ${{ matrix.assume-region }}

  print_diff:
    name: Print Diff
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      id-token: write
      pull-requests: write
    needs:
      - diff__dev
      - diff__prod
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Update PR Description
        uses: rehanvdm/cdk-express-pipeline-github-diff@feature/improve-cache
        with:
          mode: print
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cloud-assemblies: '[{"header":"CDK Diff -
            dev","directory":"cdk.out/dev"},{"header":"CDK Diff -
            prod","directory":"cdk.out/prod"}]'