name: CDK Express Pipeline Diff
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Synth
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run CDK Express Pipeline Synth
        uses: ./.github/actions/cdk-express-pipeline-synth
  diff__dev:
    name: Diff dev - ${{ matrix.name }}
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      id-token: write
      pull-requests: write
    strategy:
      matrix:
        include:
          - name: wave1
            cloud-assembly-directory: cdk.out/dev
            stack-selector-patterns: Wave1_*
            command: npm run cdk diff Wave1_* --app=cdk.out/dev
            write-as-comment: true
          - name: wave2
            cloud-assembly-directory: cdk.out/dev
            stack-selector-patterns: Wave2_*
            command: npm run cdk diff Wave2_* --app=cdk.out/dev
            write-as-comment: true
      fail-fast: false
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run CDK Express Pipeline Synth
        uses: ./.github/actions/cdk-express-pipeline-diff
        with:
          stack-selector-patterns: ${{ matrix.stack-selector-patterns }}
          cloud-assembly-directory: ${{ matrix.cloud-assembly-directory }}
          command: ${{ matrix.command }}
          write-as-comment: ${{ matrix.write-as-comment }}
          comment-title: "CDK Diff: dev - ${{ matrix.name }}"
          github-token: ${{ secrets.GITHUB_TOKEN }}
  diff__prod:
    name: Diff prod - ${{ matrix.name }}
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      id-token: write
      pull-requests: write
    strategy:
      matrix:
        include:
          - name: wave1
            cloud-assembly-directory: cdk.out/prod
            stack-selector-patterns: Wave1_*
            command: npm run cdk diff Wave1_* --app=cdk.out/prod
            write-as-comment: true
          - name: wave2
            cloud-assembly-directory: cdk.out/prod
            stack-selector-patterns: Wave2_*
            command: npm run cdk diff Wave2_* --app=cdk.out/prod
            write-as-comment: true
      fail-fast: false
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run CDK Express Pipeline Synth
        uses: ./.github/actions/cdk-express-pipeline-diff
        with:
          stack-selector-patterns: ${{ matrix.stack-selector-patterns }}
          cloud-assembly-directory: ${{ matrix.cloud-assembly-directory }}
          command: ${{ matrix.command }}
          write-as-comment: ${{ matrix.write-as-comment }}
          comment-title: "CDK Diff: prod - ${{ matrix.name }}"
          github-token: ${{ secrets.GITHUB_TOKEN }}
